<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-ECommerceApp.Notification-701c8021-0512-409b-83db-9d257a4edba5</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.16.0" />
    <PackageReference Include="MassTransit" Version="9.1.1" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="9.1.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\ECommerceApp.Shared\ECommerceApp.Shared.csproj" />
  </ItemGroup>
</Project>
